Another "fix" for #1: Dir.exists? doesn't exist in earlier versions of Ruby
@storge reported the following error:

    [crunchbang5010:storge] ~ $ ppl init ~/contacts ppl: undefined method `exists?' for Dir:Class

Apparently Dir.exists? doesn't exist (ironic) in Ruby 1.8. In the long-term this
could use a proper solution that actually fixes the problem, but in the meantime
I've added a `required_ruby_version` to the gemspec to make this requirement
explicit.